### ISSUE TITLE
Question: knowledge if firmware runs against ERST20F-VM2E?

### ISSUE THREAD

**Issue by Ocramius** [tobias-93/esphome-ecodan-heatpump#16]
Figured I'd ask here, before spending a lot of money on a massive brick 😁

I've got a quote to get a `ERST20F-VM2E` installed.

According to https://www.manualslib.com/manual/3382261/Mitsubishi-Electric-Ehpt17x-Vm2e.html?page=75&term=cn105&selected=1#manual , the heat pump uses a similar board ( `BH00V557B` ) as the VM2D models.

https://www.manualslib.com/manual/2112291/Mitsubishi-Electric-Ehst17d-Vm2d.html?page=64&term=cn105&selected=6#manual (`BH00J709B`, unless that is just an example serial number).

I'm wondering if there's any lingering knowledge about heat pump support around here 😁

**Comment by boroczkigabor** [comment]
Hi @Ocramius,

I can confirm that this works with that model, I have just installed it yesterday. I got it working with this yaml at the end:
```yaml
substitutions:
  name: mitsubishilogger
  friendly_name: Hőszivattyú

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 200
    then:
      - delay: 30s
      - switch.turn_off:
          id: eps32_s3_led_switch

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "<api key>"

ota:
  - platform: esphome
    password: "<ota password>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mitsubishilogger"
    password: "jMGeiXwLYR3z"

#captive_portal:

uart:
  id: ecodan_uart
  rx_pin:
    number: GPIO2
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO1
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1

web_server:
  port: 80

packages:
  ecodan-heatpump: github://tobias-93/esphome-ecodan-heatpump/heatpump.yaml@main

```
