### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by Rvh91** [tobias-93/esphome-ecodan-heatpump#3]
Hi,

I'm having compilation issues that I cannot fully explain.  Could you help me resolve this issue?
I'm getting the following error on compiling:

```
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanSwitch11write_stateEb+0x4): undefined reference to `ecodan::commands::command_power_state::packetMask'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanSwitch11write_stateEb+0xc): undefined reference to `ecodan::commands::command_force_dhw::packetMask'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanSelect7controlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x4): undefined reference to `ecodan::commands::command_mode_select::packetMask'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanSelect7controlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xc): undefined reference to `ecodan::commands::command_hot_water_mode::packetMask'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanNumber7controlEf+0x8): undefined reference to `ecodan::commands::command_hot_water_setpoint::packetMask'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanNumber7controlEf+0x10): undefined reference to `ecodan::commands::command_zone1_room_temp_setpoint::packetMask'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/fancontrol-eth/src/esphome/components/ecodan/ecodan.cpp.o:(.literal._ZN7esphome7ecodan_12EcodanNumber7controlEf+0x18): undefined reference to `ecodan::commands::command_zone1_flow_temp_setpoint::packetMask'
collect2: error: ld returned 1 exit status
*** [.pioenvs/fancontrol-eth/firmware.elf] Error 1
```

In my yaml I have the following:

```
external_components:
  - source: github://tobias-93/esphome-ecodan-heatpump@main
    components: [ ecodan ]

esp32:
  board: esp32dev
  framework:
    type: arduino

##....
## logger stuff
## api stuff
## OTA stuff
## ethernet configuration
## bluetooth stuff
## GPIO and PWM output stuff
##....

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 2400
  parity: EVEN
  rx_buffer_size: 1024
  id: uart_ecodan

ecodan:
  id: ecodan_instance
  uart_id: uart_ecodan

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${node_name} ESPHome Version
  - platform: ethernet_info
    ip_address:
      name: ${node_name} IP  
  - platform: ecodan
    date_time:
      name: Current date/time
    defrost:
      name: Defrost
    heating_stage:
      name: Heating stage
    operating_mode:
      name: Operating mode
    heat_cool:
      name: Heating/cooling
    hot_water_timer:
      name: Hot water timer
    date_energy_cons:
      name: Date energy consumption
    date_energy_prod:
      name: Date energy production      
    holiday_mode:
      name: Holiday mode

sensor:
  - platform: uptime
    name: Uptime
  - platform: ecodan
    error_code:
      name: Error code
    frequency:
      name: Frequency
    output_power:
      name: Output power
    zone1_room_temperature:
      name: Room temperature
    gas_return_temp_signed:
      name: Gas return temperature
    outside_temperature:
      name: Outside temperature
    water_feed_temp_signed:
      name: Water feed temperature
    water_return_temp_signed:
      name: Water return temperature
    hot_water_temperature:
      name: Hot water temperature
    runtime:
      name: Runtime
    water_flow:
      name: Water flow
    energy_cons_yesterday:
      name: Energy consumption (yesterday)
    energy_prod_yesterday:
      name: Energy production (yesterday)

select:
  - platform: ecodan
    mode_select:
      name: Mode
    hot_water_mode:
      name: Hot water mode

number:
  - platform: ecodan
    hot_water_setpoint:
      name: Hot water setpoint
    zone1_room_temp_setpoint:
      name: Room temperature setpoint
    zone1_flow_temp_setpoint:
      name: Flow temperature setpoint

switch:
  - platform: ecodan
    power_state:
      name: Power state
    force_dhw:
      name: Force DHW

```

**Comment by Rvh91** [comment]
I did manage to compile just fine on an esp01_m board. The issue seems to be board related? Which seems weird as the only IO reqruied is a uart?

**Comment by joris-kuleuven** [comment]
I have the same issue... Since I don't have access to another ESP32 board, are there any things I could try to narrow it down to a certain problem? I suspect the compilation order might cause the issue of the undefined references to symbols of `ecodan::commands`

**Comment by Petititi** [comment]
I had the same error and didn't find a way to solve this "nicely". I had to get rid of the nice macro and the `static constexpr uint8_t packetMask[PACKET_BUFFER_SIZE] = d_packetMask;` to replace them by the values... Very strange issue :-(
I end up with this at the top of ecodan.cpp:
```
static constexpr uint8_t power_state_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x32, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static constexpr uint8_t force_dhw_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x34, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static constexpr uint8_t mode_select_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x32, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static constexpr uint8_t hot_water_mode_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x32, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static constexpr uint8_t hot_water_setpoint_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x32, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static constexpr uint8_t zone1_room_temp_setpoint_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x32, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static constexpr uint8_t zone1_flow_temp_setpoint_msg[PACKET_BUFFER_SIZE] = {0xfc, 0x41, 0x02, 0x7a, 0x10, 0x32, 0x80, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
```
Then, I had to break macro like `ECODAN_SWITCH_LIST(ECODAN_WRITE_SWITCH, )` into the successive `if` statements:
```
    if (this->key_ == "power_state") {
      send = true;
      memcpy(sendBuffer, power_state_msg, PACKET_BUFFER_SIZE);
      sendBuffer[command_power_state::varIndex] = state ? 1 : 0;
    }
    if (this->key_ == "force_dhw") {
      send = true;
      memcpy(sendBuffer, force_dhw_msg, PACKET_BUFFER_SIZE);
      sendBuffer[command_force_dhw::varIndex] = state ? 1 : 0;
    }
```
😢

**Comment by franshoogeboom** [comment]
The issue is that the packetMask is odr-used but there is no definition for it, see [link](https://en.cppreference.com/w/cpp/language/static#Static_data_members) which states: "If a const non-inline(since C++17) static data member or a constexpr static data member(since C++11)(until C++17) is odr-used, a definition at namespace scope is still required, but it cannot have an initializer.". 
The issue can be solved by explicitly compiling with -std=c++17 (or later) where all static constexpr data members are implicitly inline and does not need to be redeclared at namespace scope. This can be done as follows:

```
esphome:
  ...
  platformio_options:
    build_unflags:
      - -std=gnu++11
    build_flags: 
      - -std=gnu++17
```

Another option is to add the following definitions to the top of ecodan.cpp

```
constexpr uint8_t ecodan::commands::command_power_state::packetMask[PACKET_BUFFER_SIZE];
constexpr uint8_t ecodan::commands::command_force_dhw::packetMask[PACKET_BUFFER_SIZE];
constexpr uint8_t ecodan::commands::command_mode_select::packetMask[PACKET_BUFFER_SIZE];
constexpr uint8_t ecodan::commands::command_hot_water_mode::packetMask[PACKET_BUFFER_SIZE];
constexpr uint8_t ecodan::commands::command_hot_water_setpoint::packetMask[PACKET_BUFFER_SIZE];
constexpr uint8_t ecodan::commands::command_zone1_room_temp_setpoint::packetMask[PACKET_BUFFER_SIZE];
constexpr uint8_t ecodan::commands::command_zone1_flow_temp_setpoint::packetMask[PACKET_BUFFER_SIZE];	
```
